### PR TITLE
(IAC-594) node_pools items can now add in n number of misc disks

### PR DESCRIPTION
**Pull request by thpang**
Add in code to add n number of misc disks to a vm when identified in the node_pools configuration. Also added in the skeleton for the container registry VM.

### CODE REVIEW

**Comment by sayeun** [comment]
@thpang - maybe it's easier to schedule a group review meeting on this one.

**Review by jarpat — APPROVED** [review]
+1, we had a code review meeting.

**Comment by thpang** [comment]
@riragh can you approve these changes? David did not before he left for vacation. Jay has already given his thumbs up. Thx.

**Review by riragh — APPROVED** [review]
LGTM

**Pull request merged**
