### PR TITLE
Move creation of /export/pvs directory into NFS server role

### PR DESCRIPTION
**Pull request by AWSmith0216**
For an on-prem cluster, the value of the jump server is less clear to me than for the cloud providers. If using ansible to stage all the systems, you pretty much by definition have SSH access to all systems, so the jump server isn't required as an entry point into the cluster. Users may also have limited compute resources, so there could be a desire to eliminate the jump server if unneeded.

For my use cases, I'd like to eliminate this server. Simply not assigning an instance to the jump server role seems like the obvious way to do so, and works well enough for this specific project, but would cause complications when baselining with viya4-deployment. That project, when creating the **sas** storage class, expects _/export/pvs_ to exist on the NFS server. When the cluster is created, the NFS server role creates _/export_:

https://github.com/sassoftware/viya4-iac-k8s/blob/main/roles/systems/nfs_server/tasks/main.yaml#L18

However, the jump server role creates _/export/pvs_:

https://github.com/sassoftware/viya4-iac-k8s/blob/main/roles/systems/jump_server/tasks/main.yaml#L88

It's not clear to me why it's done this way, other than for consistency with the external cloud provider viya4-iac-* projects. That being said, I don't know why it's done that way for those projects either, but perhaps there's good reason I'm unaware of.

I can see no technical reason that the jump server is responsible for creating _/export/pvs_, and to me it's unintuitive. It also makes the jump server basically required to complete the NFS server setup. With the proposed change, the jump server can still act as the entry point into the cluster, the mounts are still setup, but the NFS server role can stand alone and fulfill it's function for the **sas** and **default** SCs.

### CODE REVIEW

**Comment by AWSmith0216** [comment]
Would seem this PR was closed when the staging branch was deleted. Was that intentional? Otherwise I can re-open when/if the staging branch is recreated.

**Comment by jarpat** [comment]
@AWSmith0216 I did not expect it to automatically close this PR when staging was deleted. I've recreated the staging branch, could you please re-open the PR?

**Comment by AWSmith0216** [comment]
Thanks. It's been re-opened.

**Comment by thpang** [comment]
For this code base this would work; however, when one chooses an enterprise level solution for their storage, i.e. other cloud providers this work flow breaks. There is not actual nfs server therefore I am closing this one.

**Pull request closed without merging**
