### PR TITLE
chore: (IAC-1306) Add Bug Report Form

### PR DESCRIPTION
**Pull request by jarpat**
### Changes

Add bug report form

### CODE REVIEW

**Review by riragh — APPROVED** [review]

**Review by dhoucgitter — APPROVED** [review]

**Comment by dhoucgitter** [comment]
This looks good @jarpat, wondering if you know of any way for us to hide/remove the option for creating a blank issue when folks are presented with both the "Get Started" green button that uses this template and the blue "Open a blank issue" which does not. Unfortunately, the blue link is what people end up using in my experience which is not ideal for us.
image

**Comment by sayeun** [comment]
@dhoucgitter - like this https://docs.github.com/en/enterprise-server@3.8/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by jarpat** [comment]
@dhoucgitter & @sayeun I'll take a look at that link

**Comment by jarpat** [comment]
@sayeun That looks like it works to eliminate the "blank issues", a small change is needed, the extension needs to be `yml` rather than `yaml`.

I'll also create add a generic feature request issue based on the default one from GitHub since bugs are not the only thing that users will report. I'll make the additons and ask for reviews again.

**Comment by jarpat** [comment]
@sayeun, @dhoucgitter, @thpang, @riragh this is ready for re-review. Added the suggestion to remove the "blank issues" option so we have more structured issues from users. Also added a generic feature request template.

Tried it out in my test repo, it will render like this:
image
---
image

**Review by thpang — APPROVED** [review]
LGTM

**Pull request merged**
