### PR TITLE
docs: (IAC-671) Update kube-vip URL

### PR DESCRIPTION
**Pull request by jarpat**
## Changes
`https://kube-vip.chipzoller.dev` should now be `https://kube-vip.io`

## Tests

Verified the updated URLs lead to the correct page & section

### CODE REVIEW

**Review by riragh — APPROVED** [review]
LGTM

**Review by sayeun — APPROVED** [review]
I tried out all the new links, they all worked.

**Review by dhoucgitter — APPROVED** [review]
lgtm

**Review by thpang — APPROVED** [review]
LGTM

**Pull request merged**
